### ISSUE TITLE
OAuth login logging event

### ISSUE THREAD

**Issue by Randomblock1** [Rakambda/ChannelPointsMiner#530]
### Description

It would be really useful to have a logging event fire off when OAuth login is needed. I'm running this in a Docker container so if the machine restarts or the image updates I don't immediately know if I need to enter another login code. Adding some sort of logging event would let me get notified via Discord, for example.

**Comment by Rakambda** [comment]
What do you mean by `logging event`? There's already a log when it happens and tools like syslog can firenotification when it appears.
https://github.com/Rakambda/ChannelPointsMiner/blob/develop/miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/passport/oauth/OauthLoginProvider.java#L72


Do you mean like a proper event because you make your own code around it? A discord message?

**Comment by Randomblock1** [comment]
Yes, a proper event, I want it to send a Discord message. AFAIK there's no way to do that currently.

**Comment by Rakambda** [comment]
Can you try with the `530-oauth-login-logging-event` docker tag and see if it meets your needs ?

**Comment by Randomblock1** [comment]
It works but if possible I'd like to have it send the link and code too (easier to click a Discord link than ssh'ing and looking at docker logs). Thanks!

**Comment by Rakambda** [comment]
Done, will release it in the develop branch. If no issues are found in like a week then it'll be released properly.
